{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1018)","timestamp":"2025-02-19 19:10:55,843+0530","service":"FyersDataSocket"}
{"level":"DEBUG","location":"[<lambda>:1664] data_ws","message":"Response:Attempting reconnect 1 of 5...","timestamp":"2025-02-19 19:10:55,850+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1018)","timestamp":"2025-02-19 19:11:00,897+0530","service":"FyersDataSocket"}
{"level":"DEBUG","location":"[<lambda>:1664] data_ws","message":"Response:Attempting reconnect 2 of 5...","timestamp":"2025-02-19 19:11:00,898+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1018)","timestamp":"2025-02-19 19:11:05,948+0530","service":"FyersDataSocket"}
{"level":"DEBUG","location":"[<lambda>:1664] data_ws","message":"Response:Attempting reconnect 3 of 5...","timestamp":"2025-02-19 19:11:05,951+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1018)","timestamp":"2025-02-19 19:11:10,998+0530","service":"FyersDataSocket"}
{"level":"DEBUG","location":"[<lambda>:1664] data_ws","message":"Response:Attempting reconnect 4 of 5...","timestamp":"2025-02-19 19:11:10,998+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1018)","timestamp":"2025-02-19 19:11:16,515+0530","service":"FyersDataSocket"}
{"level":"DEBUG","location":"[<lambda>:1664] data_ws","message":"Response:Attempting reconnect 5 of 5...","timestamp":"2025-02-19 19:11:16,519+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1018)","timestamp":"2025-02-19 19:11:21,569+0530","service":"FyersDataSocket"}
{"level":"DEBUG","location":"[<lambda>:1664] data_ws","message":"Response:Max reconnect attempts reached. Connection abandoned.","timestamp":"2025-02-19 19:11:21,570+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1018)","timestamp":"2025-02-19 21:32:36,736+0530","service":"FyersDataSocket"}
{"level":"DEBUG","location":"[<lambda>:1664] data_ws","message":"Response:Attempting reconnect 1 of 5...","timestamp":"2025-02-19 21:32:36,745+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1018)","timestamp":"2025-02-19 21:32:41,794+0530","service":"FyersDataSocket"}
{"level":"DEBUG","location":"[<lambda>:1664] data_ws","message":"Response:Attempting reconnect 2 of 5...","timestamp":"2025-02-19 21:32:41,798+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1018)","timestamp":"2025-02-19 21:32:46,850+0530","service":"FyersDataSocket"}
{"level":"DEBUG","location":"[<lambda>:1664] data_ws","message":"Response:Attempting reconnect 3 of 5...","timestamp":"2025-02-19 21:32:46,851+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1018)","timestamp":"2025-02-19 21:32:51,895+0530","service":"FyersDataSocket"}
{"level":"DEBUG","location":"[<lambda>:1664] data_ws","message":"Response:Attempting reconnect 4 of 5...","timestamp":"2025-02-19 21:32:51,898+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1018)","timestamp":"2025-02-19 21:32:56,959+0530","service":"FyersDataSocket"}
{"level":"DEBUG","location":"[<lambda>:1664] data_ws","message":"Response:Attempting reconnect 5 of 5...","timestamp":"2025-02-19 21:32:56,959+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1018)","timestamp":"2025-02-19 21:33:02,002+0530","service":"FyersDataSocket"}
{"level":"DEBUG","location":"[<lambda>:1664] data_ws","message":"Response:Max reconnect attempts reached. Connection abandoned.","timestamp":"2025-02-19 21:33:02,002+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1018)","timestamp":"2025-02-19 21:44:19,251+0530","service":"FyersDataSocket"}
{"level":"DEBUG","location":"[<lambda>:1664] data_ws","message":"Response:Attempting reconnect 1 of 5...","timestamp":"2025-02-19 21:44:19,257+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1018)","timestamp":"2025-02-19 21:44:24,306+0530","service":"FyersDataSocket"}
{"level":"DEBUG","location":"[<lambda>:1664] data_ws","message":"Response:Attempting reconnect 2 of 5...","timestamp":"2025-02-19 21:44:24,308+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1018)","timestamp":"2025-02-19 21:44:29,347+0530","service":"FyersDataSocket"}
{"level":"DEBUG","location":"[<lambda>:1664] data_ws","message":"Response:Attempting reconnect 3 of 5...","timestamp":"2025-02-19 21:44:29,348+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1018)","timestamp":"2025-02-19 21:44:34,389+0530","service":"FyersDataSocket"}
{"level":"DEBUG","location":"[<lambda>:1664] data_ws","message":"Response:Attempting reconnect 4 of 5...","timestamp":"2025-02-19 21:44:34,391+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[access_token_to_hsmtoken:272] data_ws","message":{"type":"cn","code":-99,"message":"Token is expired","s":"error"},"timestamp":"2025-02-20 15:03:06,450+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1018)","timestamp":"2025-02-20 15:07:15,781+0530","service":"FyersDataSocket"}
{"level":"DEBUG","location":"[<lambda>:1664] data_ws","message":"Response:Attempting reconnect 1 of 5...","timestamp":"2025-02-20 15:07:15,785+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1018)","timestamp":"2025-02-20 15:07:20,851+0530","service":"FyersDataSocket"}
{"level":"DEBUG","location":"[<lambda>:1664] data_ws","message":"Response:Attempting reconnect 2 of 5...","timestamp":"2025-02-20 15:07:20,851+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1018)","timestamp":"2025-02-20 15:07:45,952+0530","service":"FyersDataSocket"}
{"level":"DEBUG","location":"[<lambda>:1664] data_ws","message":"Response:Attempting reconnect 1 of 5...","timestamp":"2025-02-20 15:07:45,956+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1018)","timestamp":"2025-02-20 15:07:51,009+0530","service":"FyersDataSocket"}
{"level":"DEBUG","location":"[<lambda>:1664] data_ws","message":"Response:Attempting reconnect 2 of 5...","timestamp":"2025-02-20 15:07:51,010+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1018)","timestamp":"2025-02-20 15:07:56,049+0530","service":"FyersDataSocket"}
{"level":"DEBUG","location":"[<lambda>:1664] data_ws","message":"Response:Attempting reconnect 3 of 5...","timestamp":"2025-02-20 15:07:56,049+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1018)","timestamp":"2025-02-20 15:08:01,113+0530","service":"FyersDataSocket"}
{"level":"DEBUG","location":"[<lambda>:1664] data_ws","message":"Response:Attempting reconnect 4 of 5...","timestamp":"2025-02-20 15:08:01,115+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1018)","timestamp":"2025-02-20 15:08:06,152+0530","service":"FyersDataSocket"}
{"level":"DEBUG","location":"[<lambda>:1664] data_ws","message":"Response:Attempting reconnect 5 of 5...","timestamp":"2025-02-20 15:08:06,153+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1018)","timestamp":"2025-02-20 15:08:11,184+0530","service":"FyersDataSocket"}
{"level":"DEBUG","location":"[<lambda>:1664] data_ws","message":"Response:Max reconnect attempts reached. Connection abandoned.","timestamp":"2025-02-20 15:08:11,185+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1018)","timestamp":"2025-02-20 15:16:03,758+0530","service":"FyersDataSocket"}
{"level":"DEBUG","location":"[<lambda>:1664] data_ws","message":"Response:Attempting reconnect 1 of 5...","timestamp":"2025-02-20 15:16:03,761+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1018)","timestamp":"2025-02-20 15:21:57,258+0530","service":"FyersDataSocket"}
{"level":"DEBUG","location":"[<lambda>:1664] data_ws","message":"Response:Attempting reconnect 1 of 5...","timestamp":"2025-02-20 15:21:57,265+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1018)","timestamp":"2025-02-20 15:22:02,310+0530","service":"FyersDataSocket"}
{"level":"DEBUG","location":"[<lambda>:1664] data_ws","message":"Response:Attempting reconnect 2 of 5...","timestamp":"2025-02-20 15:22:02,310+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1018)","timestamp":"2025-02-20 15:22:07,353+0530","service":"FyersDataSocket"}
{"level":"DEBUG","location":"[<lambda>:1664] data_ws","message":"Response:Attempting reconnect 3 of 5...","timestamp":"2025-02-20 15:22:07,354+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1018)","timestamp":"2025-02-20 15:22:52,649+0530","service":"FyersDataSocket"}
{"level":"DEBUG","location":"[<lambda>:1664] data_ws","message":"Response:Attempting reconnect 1 of 5...","timestamp":"2025-02-20 15:22:52,656+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1018)","timestamp":"2025-02-20 15:22:57,721+0530","service":"FyersDataSocket"}
{"level":"DEBUG","location":"[<lambda>:1664] data_ws","message":"Response:Attempting reconnect 2 of 5...","timestamp":"2025-02-20 15:22:57,722+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1018)","timestamp":"2025-02-20 15:23:02,817+0530","service":"FyersDataSocket"}
{"level":"DEBUG","location":"[<lambda>:1664] data_ws","message":"Response:Attempting reconnect 3 of 5...","timestamp":"2025-02-20 15:23:02,820+0530","service":"FyersDataSocket"}
